# Challenge 1 - Tic Tac Toe

In this lab you will perform deep learning analysis on a dataset of playing [Tic Tac Toe](https://en.wikipedia.org/wiki/Tic-tac-toe).

There are 9 grids in Tic Tac Toe that are coded as the following picture shows:

![Tic Tac Toe Grids](tttboard.jpg)

In the first 9 columns of the dataset you can find which marks (`x` or `o`) exist in the grids. If there is no mark in a certain grid, it is labeled as `b`. The last column is `class` which tells you whether Player X (who always moves first in Tic Tac Toe) wins in this configuration. Note that when `class` has the value `False`, it means either Player O wins the game or it ends up as a draw.

Follow the steps suggested below to conduct a neural network analysis using Tensorflow and Keras. You will build a deep learning model to predict whether Player X wins the game or not.

## Step 1: Data Engineering

This dataset is almost in the ready-to-use state so you do not need to worry about missing values and so on. Still, some simple data engineering is needed.

1. Read `tic-tac-toe.csv` into a dataframe.
1. Inspect the dataset. Determine if the dataset is reliable by eyeballing the data.
1. Convert the categorical values to numeric in all columns.
1. Separate the inputs and output.
1. Normalize the input data.

In [93]:
# your code here
import pandas as pd
import numpy as np

tictac = pd.read_csv('tic-tac-toe.csv')
tictac.head()

  TL TM TR ML MM MR BL BM BR  class
0  x  x  x  x  o  o  x  o  o   True
1  x  x  x  x  o  o  o  x  o   True
2  x  x  x  x  o  o  o  o  x   True
3  x  x  x  x  o  o  o  b  b   True
4  x  x  x  x  o  o  b  o  b   True

In [94]:
tictac.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 958 entries, 0 to 957
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   TL      958 non-null    object
 1   TM      958 non-null    object
 2   TR      958 non-null    object
 3   ML      958 non-null    object
 4   MM      958 non-null    object
 5   MR      958 non-null    object
 6   BL      958 non-null    object
 7   BM      958 non-null    object
 8   BR      958 non-null    object
 9   class   958 non-null    bool
dtypes: bool(1), object(9)
memory usage: 68.4+ KB

In [95]:
tictac['TL'].value_counts()

x    418
o    335
b    205
Name: TL, dtype: int64

In [96]:
def numerical(row):
    if row == 'b':
        return -1
    elif row == 'x':
        return 0
    else:
        return 1

In [97]:
tictac[tictac['class'] == False]

    TL TM TR ML MM MR BL BM BR  class
626  x  x  o  x  x  o  o  b  o  False
627  x  x  o  x  x  o  b  o  o  False
628  x  x  o  x  x  b  o  o  o  False
629  x  x  o  x  o  x  o  o  b  False
630  x  x  o  x  o  x  o  b  o  False
..  .. .. .. .. .. .. .. .. ..    ...
953  o  x  x  x  o  o  o  x  x  False
954  o  x  o  x  x  o  x  o  x  False
955  o  x  o  x  o  x  x  o  x  False
956  o  x  o  o  x  x  x  o  x  False
957  o  o  x  x  x  o  o  x  x  False

[332 rows x 10 columns]

In [98]:
for column in list(tictac.columns[:-1]):
    tictac[column] = tictac[column].apply(numerical)
    
tictac.head()

   TL  TM  TR  ML  MM  MR  BL  BM  BR  class
0   0   0   0   0   1   1   0   1   1   True
1   0   0   0   0   1   1   1   0   1   True
2   0   0   0   0   1   1   1   1   0   True
3   0   0   0   0   1   1   1  -1  -1   True
4   0   0   0   0   1   1  -1   1  -1   True

## Step 2: Build Neural Network

To build the neural network, you can refer to your own codes you wrote while following the [Deep Learning with Python, TensorFlow, and Keras tutorial](https://www.youtube.com/watch?v=wQ8BIBpya2k) in the lesson. It's pretty similar to what you will be doing in this lab.

1. Split the training and test data.
1. Create a `Sequential` model.
1. Add several layers to your model. Make sure you use ReLU as the activation function for the middle layers. Use Softmax for the output layer because each output has a single lable and all the label probabilities add up to 1.
1. Compile the model using `adam` as the optimizer and `sparse_categorical_crossentropy` as the loss function. For metrics, use `accuracy` for now.
1. Fit the training data.
1. Evaluate your neural network model with the test data.
1. Save your model as `tic-tac-toe.model`.

In [99]:
# your code here
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(tictac[tictac.columns[:-1]], tictac['class'],test_size = 0.2, random_state=29)

In [121]:
from keras.models import Sequential
from keras.layers import Dense
from tensorflow.keras.utils import to_categorical
import tensorflow as tf

In [117]:
tictac_model = Sequential([
  Dense(48, activation='relu'),
  Dense(48, activation='relu'),
  Dense(8, activation='softmax'),   
])

tictac_model.compile(
  optimizer='adam',
  loss='sparse_categorical_crossentropy',
  metrics=['accuracy'],
)

history = tictac_model.fit(
  X_train,
  y_train,
  epochs=50,
  batch_size=8,
)

tictac_model.evaluate(
  X_test,
  y_test
)

Epoch 1/50
96/96 [==============================] - 1s 4ms/step - loss: 1.2068 - accuracy: 0.5822
Epoch 2/50
96/96 [==============================] - 0s 4ms/step - loss: 0.6106 - accuracy: 0.6919
Epoch 3/50
96/96 [==============================] - 0s 4ms/step - loss: 0.5482 - accuracy: 0.7167
Epoch 4/50
96/96 [==============================] - 0s 3ms/step - loss: 0.5136 - accuracy: 0.7206
Epoch 5/50
96/96 [==============================] - 0s 3ms/step - loss: 0.4841 - accuracy: 0.7467
Epoch 6/50
96/96 [==============================] - 0s 2ms/step - loss: 0.4573 - accuracy: 0.7715
Epoch 7/50
96/96 [==============================] - 0s 2ms/step - loss: 0.4354 - accuracy: 0.7637
Epoch 8/50
96/96 [==============================] - 0s 2ms/step - loss: 0.4070 - accuracy: 0.7937
Epoch 9/50
96/96 [==============================] - 0s 2ms/step - loss: 0.3844 - accuracy: 0.8120
Epoch 10/50
96/96 [==============================] - 0s 2ms/step - loss: 0.3596 - accuracy: 0.8329
Epoch 11/50
96/96 [==============================] - 0s 2ms/step - loss: 0.3363 - accuracy: 0.8460
Epoch 12/50
96/96 [==============================] - 0s 2ms/step - loss: 0.3145 - accuracy: 0.8551
Epoch 13/50
96/96 [==============================] - 0s 2ms/step - loss: 0.3002 - accuracy: 0.8825
Epoch 14/50
96/96 [==============================] - 0s 2ms/step - loss: 0.2862 - accuracy: 0.8773
Epoch 15/50
96/96 [==============================] - 0s 2ms/step - loss: 0.2664 - accuracy: 0.8903
Epoch 16/50
96/96 [==============================] - 0s 2ms/step - loss: 0.2507 - accuracy: 0.8903
Epoch 17/50
96/96 [==============================] - 0s 2ms/step - loss: 0.2378 - accuracy: 0.9008
Epoch 18/50
96/96 [==============================] - 0s 2ms/step - loss: 0.2260 - accuracy: 0.9112
Epoch 19/50
96/96 [==============================] - 0s 2ms/step - loss: 0.2080 - accuracy: 0.9217
Epoch 20/50
96/96 [==============================] - 0s 2ms/step - loss: 0.1968 - accuracy: 0.9243
Epoch 21/50
96/96 [==============================] - 0s 2ms/step - loss: 0.1822 - accuracy: 0.9399
Epoch 22/50
96/96 [==============================] - 0s 2ms/step - loss: 0.1737 - accuracy: 0.9373
Epoch 23/50
96/96 [==============================] - 0s 2ms/step - loss: 0.1583 - accuracy: 0.9478
Epoch 24/50
96/96 [==============================] - 0s 2ms/step - loss: 0.1444 - accuracy: 0.9595
Epoch 25/50
96/96 [==============================] - 0s 2ms/step - loss: 0.1354 - accuracy: 0.9582
Epoch 26/50
96/96 [==============================] - 0s 2ms/step - loss: 0.1290 - accuracy: 0.9648
Epoch 27/50
96/96 [==============================] - 0s 2ms/step - loss: 0.1205 - accuracy: 0.9661
Epoch 28/50
96/96 [==============================] - 0s 2ms/step - loss: 0.1110 - accuracy: 0.9634
Epoch 29/50
96/96 [==============================] - 0s 2ms/step - loss: 0.1039 - accuracy: 0.9739
Epoch 30/50
96/96 [==============================] - 0s 2ms/step - loss: 0.0959 - accuracy: 0.9752
Epoch 31/50
96/96 [==============================] - 0s 2ms/step - loss: 0.0899 - accuracy: 0.9804
Epoch 32/50
96/96 [==============================] - 0s 2ms/step - loss: 0.0836 - accuracy: 0.9817
Epoch 33/50
96/96 [==============================] - 0s 2ms/step - loss: 0.0814 - accuracy: 0.9804
Epoch 34/50
96/96 [==============================] - 0s 2ms/step - loss: 0.0719 - accuracy: 0.9830
Epoch 35/50
96/96 [==============================] - 0s 2ms/step - loss: 0.0734 - accuracy: 0.9843
Epoch 36/50
96/96 [==============================] - 0s 2ms/step - loss: 0.0662 - accuracy: 0.9804
Epoch 37/50
96/96 [==============================] - 0s 2ms/step - loss: 0.0644 - accuracy: 0.9883
Epoch 38/50
96/96 [==============================] - 0s 2ms/step - loss: 0.0541 - accuracy: 0.9896
Epoch 39/50
96/96 [==============================] - 0s 2ms/step - loss: 0.0510 - accuracy: 0.9909
Epoch 40/50
96/96 [==============================] - 0s 2ms/step - loss: 0.0486 - accuracy: 0.9922
Epoch 41/50
96/96 [==============================] - 0s 2ms/step - loss: 0.0444 - accuracy: 0.9909
Epoch 42/50
96/96 [==============================] - 0s 2ms/step - loss: 0.0410 - accuracy: 0.9948
Epoch 43/50
96/96 [==============================] - 0s 2ms/step - loss: 0.0400 - accuracy: 0.9948
Epoch 44/50
96/96 [==============================] - 0s 2ms/step - loss: 0.0361 - accuracy: 0.9948
Epoch 45/50
96/96 [==============================] - 0s 2ms/step - loss: 0.0342 - accuracy: 0.9961
Epoch 46/50
96/96 [==============================] - 0s 2ms/step - loss: 0.0318 - accuracy: 0.9974
Epoch 47/50
96/96 [==============================] - 0s 2ms/step - loss: 0.0296 - accuracy: 0.9961
Epoch 48/50
96/96 [==============================] - 0s 2ms/step - loss: 0.0292 - accuracy: 0.9961
Epoch 49/50
96/96 [==============================] - 0s 2ms/step - loss: 0.0252 - accuracy: 0.9987
Epoch 50/50
96/96 [==============================] - 0s 2ms/step - loss: 0.0232 - accuracy: 1.0000
6/6 [==============================] - 0s 3ms/step - loss: 0.1679 - accuracy: 0.9219

[0.16791468858718872, 0.921875]

## Step 3: Make Predictions

Now load your saved model and use it to make predictions on a few random rows in the test dataset. Check if the predictions are correct.

In [120]:
# your code here
predictions = tictac_model.predict(X_test[:20])
print(np.argmax(predictions, axis=1))

[0 1 0 1 0 0 1 1 0 0 1 0 1 1 0 1 1 0 1 1]

## Step 4: Improve Your Model

Did your model achieve low loss (<0.1) and high accuracy (>0.95)? If not, try to improve your model.

But how? There are so many things you can play with in Tensorflow and in the next challenge you'll learn about these things. But in this challenge, let's just do a few things to see if they will help.

* Add more layers to your model. If the data are complex you need more layers. But don't use more layers than you need. If adding more layers does not improve the model performance you don't need additional layers.
* Adjust the learning rate when you compile the model. This means you will create a custom `tf.keras.optimizers.Adam` instance where you specify the learning rate you want. Then pass the instance to `model.compile` as the optimizer.
    * `tf.keras.optimizers.Adam` [reference](https://www.tensorflow.org/api_docs/python/tf/keras/optimizers/Adam).
    * Don't worry if you don't understand what the learning rate does. You'll learn about it in the next challenge.
* Adjust the number of epochs when you fit the training data to the model. Your model performance continues to improve as you train more epochs. But eventually it will reach the ceiling and the performance will stay the same.

In [129]:
# your code here
tictac_model = Sequential([
  Dense(48, activation='relu'),
  Dense(48, activation='relu'),
  Dense(8, activation='softmax'),   
])

opt = tf.keras.optimizers.Adam(
    learning_rate=0.001,
    beta_1=0.9,
    beta_2=0.999,
    epsilon=1e-07,
    amsgrad=False,
    name='Adam'
)


tictac_model.compile(
  optimizer=opt,
  loss='sparse_categorical_crossentropy',
  metrics=['accuracy'],
)

history = tictac_model.fit(
  X_train,
  y_train,
  epochs=50,
  batch_size=8,
)

tictac_model.evaluate(
  X_test,
  y_test
)

#Actually is worse, 0.92 vs 0.87

Epoch 1/50
96/96 [==============================] - 1s 2ms/step - loss: 1.2516 - accuracy: 0.5470
Epoch 2/50
96/96 [==============================] - 0s 2ms/step - loss: 0.5946 - accuracy: 0.6841
Epoch 3/50
96/96 [==============================] - 0s 2ms/step - loss: 0.5311 - accuracy: 0.7232
Epoch 4/50
96/96 [==============================] - 0s 2ms/step - loss: 0.4995 - accuracy: 0.7376
Epoch 5/50
96/96 [==============================] - 0s 2ms/step - loss: 0.4740 - accuracy: 0.7572
Epoch 6/50
96/96 [==============================] - 0s 2ms/step - loss: 0.4456 - accuracy: 0.7742
Epoch 7/50
96/96 [==============================] - 0s 2ms/step - loss: 0.4256 - accuracy: 0.7833
Epoch 8/50
96/96 [==============================] - 0s 2ms/step - loss: 0.4041 - accuracy: 0.8107
Epoch 9/50
96/96 [==============================] - 0s 2ms/step - loss: 0.3822 - accuracy: 0.8316
Epoch 10/50
96/96 [==============================] - 0s 2ms/step - loss: 0.3648 - accuracy: 0.8355
Epoch 11/50
96/96 [==============================] - 0s 2ms/step - loss: 0.3457 - accuracy: 0.8499
Epoch 12/50
96/96 [==============================] - 0s 2ms/step - loss: 0.3278 - accuracy: 0.8681
Epoch 13/50
96/96 [==============================] - 0s 2ms/step - loss: 0.3145 - accuracy: 0.8760
Epoch 14/50
96/96 [==============================] - 0s 2ms/step - loss: 0.2938 - accuracy: 0.8956
Epoch 15/50
96/96 [==============================] - 0s 2ms/step - loss: 0.2805 - accuracy: 0.8943
Epoch 16/50
96/96 [==============================] - 0s 2ms/step - loss: 0.2644 - accuracy: 0.9073
Epoch 17/50
96/96 [==============================] - 0s 2ms/step - loss: 0.2482 - accuracy: 0.9060
Epoch 18/50
96/96 [==============================] - 0s 2ms/step - loss: 0.2368 - accuracy: 0.9138
Epoch 19/50
96/96 [==============================] - 0s 2ms/step - loss: 0.2295 - accuracy: 0.9138
Epoch 20/50
96/96 [==============================] - 0s 2ms/step - loss: 0.2169 - accuracy: 0.9204
Epoch 21/50
96/96 [==============================] - 0s 2ms/step - loss: 0.2010 - accuracy: 0.9308
Epoch 22/50
96/96 [==============================] - 0s 2ms/step - loss: 0.1888 - accuracy: 0.9386
Epoch 23/50
96/96 [==============================] - 0s 2ms/step - loss: 0.1794 - accuracy: 0.9386
Epoch 24/50
96/96 [==============================] - 0s 2ms/step - loss: 0.1687 - accuracy: 0.9439
Epoch 25/50
96/96 [==============================] - 0s 2ms/step - loss: 0.1623 - accuracy: 0.9465
Epoch 26/50
96/96 [==============================] - 0s 2ms/step - loss: 0.1530 - accuracy: 0.9569
Epoch 27/50
96/96 [==============================] - 0s 2ms/step - loss: 0.1421 - accuracy: 0.9608
Epoch 28/50
96/96 [==============================] - 0s 2ms/step - loss: 0.1393 - accuracy: 0.9556
Epoch 29/50
96/96 [==============================] - 0s 2ms/step - loss: 0.1321 - accuracy: 0.9582
Epoch 30/50
96/96 [==============================] - 0s 2ms/step - loss: 0.1237 - accuracy: 0.9648
Epoch 31/50
96/96 [==============================] - 0s 2ms/step - loss: 0.1161 - accuracy: 0.9713
Epoch 32/50
96/96 [==============================] - 0s 2ms/step - loss: 0.1112 - accuracy: 0.9674
Epoch 33/50
96/96 [==============================] - 0s 2ms/step - loss: 0.0990 - accuracy: 0.9778
Epoch 34/50
96/96 [==============================] - 0s 2ms/step - loss: 0.0950 - accuracy: 0.9791
Epoch 35/50
96/96 [==============================] - 0s 2ms/step - loss: 0.0905 - accuracy: 0.9765
Epoch 36/50
96/96 [==============================] - 0s 2ms/step - loss: 0.0860 - accuracy: 0.9830
Epoch 37/50
96/96 [==============================] - 0s 2ms/step - loss: 0.0786 - accuracy: 0.9804
Epoch 38/50
96/96 [==============================] - 0s 2ms/step - loss: 0.0758 - accuracy: 0.9883
Epoch 39/50
96/96 [==============================] - 0s 2ms/step - loss: 0.0703 - accuracy: 0.9843
Epoch 40/50
96/96 [==============================] - 0s 2ms/step - loss: 0.0648 - accuracy: 0.9896
Epoch 41/50
96/96 [==============================] - 0s 2ms/step - loss: 0.0632 - accuracy: 0.9909
Epoch 42/50
96/96 [==============================] - 0s 2ms/step - loss: 0.0555 - accuracy: 0.9987
Epoch 43/50
96/96 [==============================] - 0s 2ms/step - loss: 0.0545 - accuracy: 0.9909
Epoch 44/50
96/96 [==============================] - 0s 2ms/step - loss: 0.0491 - accuracy: 0.9974
Epoch 45/50
96/96 [==============================] - 0s 2ms/step - loss: 0.0452 - accuracy: 0.9961
Epoch 46/50
96/96 [==============================] - 0s 2ms/step - loss: 0.0453 - accuracy: 0.9961
Epoch 47/50
96/96 [==============================] - 0s 2ms/step - loss: 0.0421 - accuracy: 0.9987
Epoch 48/50
96/96 [==============================] - 0s 2ms/step - loss: 0.0411 - accuracy: 0.9961
Epoch 49/50
96/96 [==============================] - 0s 2ms/step - loss: 0.0383 - accuracy: 0.9987
Epoch 50/50
96/96 [==============================] - 0s 2ms/step - loss: 0.0347 - accuracy: 0.9987
6/6 [==============================] - 0s 3ms/step - loss: 0.2405 - accuracy: 0.8750

[0.24054379761219025, 0.875]

**Which approach(es) did you find helpful to improve your model performance?**

In [104]:
# your answer here
# reduce batch size, add epochs, increase relu and softmax activation